---
title: "logit_RP"
output: pdf_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(readxl)
library(tidyverse)
library(epiR)
library(ggplot2)
library(gdata)
library(nnet)
library(reshape2)
library(MASS)
memory.limit(size = 200000)

# UK Geographies: https://www.ons.gov.uk/methodology/geography/ukgeographies/censusgeography#output-area-oa
# UK Geographies: http://infuse.ukdataservice.ac.uk/help/definitions/2011geographies/index.html 

# acquiring data (name row variable changed in csv (original Ist row here removed))


```
* Homogeneity (ethnic or ses) can be considered as an ordinal variable which order is meaningful and fits the condition for ordered logit
* Ordinal logit, using polr() from MASS package


```{r dataset, echo=TRUE, include = TRUE}
wd <- setwd("C:/Users/rocpa/OneDrive/Desktop/MW/mLBRENT/discrete_choice-master/multinomial ordinal regression/")
data <- read.csv("brent3.csv",sep = ";",skip = 1)
data$GEO_LABEL <- factor(data$GEO_LABEL)

# aggregate (sum) to have  ethnicityXses, 3 level each. Ses aggregated as UK census lines (high ses = 1+2; medium ses = 3+4+5, low ses = 6+7 )

data$w_hs <- data$w_1 + data$w_2
data$b_hs <- data$b_1 + data$b_2
data$a_hs <- data$a_1 + data$a_2

data$w_ms <- data$w_3 + data$w_4 + data$w_5
data$b_ms <- data$b_3 + data$b_4 + data$b_5
data$a_ms <- data$a_3 + data$a_4 + data$a_5

data$w_ls <- data$w_6 + data$w_7
data$b_ls <- data$b_6 + data$b_7
data$a_ls <- data$a_6 + data$a_7

# tot ethnicity (aggegate social class with same ethnicity)

data$w <- data$w_1 + data$w_2 + data$w_3 + data$w_4 + data$w_5 + data$w_6 + data$w_7 # white
data$b <- data$b_1 + data$b_2 + data$b_3 + data$b_4 + data$b_5 + data$b_6 + data$b_7 # black
data$a <- data$a_1 + data$a_2 + data$a_3 + data$a_4 + data$a_5 + data$a_6 + data$a_7 # asian

# tot ses (aggregate ethnicities with same ses)

data$h <- data$w_hs + data$b_hs + data$a_hs # high
data$m <- data$w_ms + data$b_ms + data$a_ms # medium
data$l <- data$w_ls + data$b_ls + data$a_ls # low

# here total population, adding the subtotal of ethnic groups

data$tot <- data$w + data$b + data$a

# computing ethnic concentration for each ethnic group

data$frac_white <- data$w/data$tot #round(data$w/data$tot, digits = 2)
data$frac_black <- data$b/data$tot #round(data$b/data$tot, digits = 2)
data$frac_asian <- data$a/data$tot #round(data$a/data$tot, digits = 2)
data$tot_frac <- data$frac_white + data$frac_black + data$frac_asian  # total to check = 1

# computing ses concentration for each ses class

data$frac_high <- data$h/data$tot
data$frac_mid  <- data$m/data$tot
data$frac_low  <- data$l/data$tot
data$tot_class <- data$h/data$tot + data$m/data$tot + data$l/data$tot # total to check = 1

# computing entropy index Simpson

data$ethdiv <-  1 - ( ((data$w * (data$w - 1)) + (data$b * (data$b - 1)) + (data$a * (data$a - 1))) / (data$tot * (data$tot - 1))  )
data$sesdiv <- 1 - ( ((data$h * (data$h - 1)) + (data$m * (data$m - 1)) + (data$l * (data$l - 1))) / (data$tot * (data$tot - 1))  )


# ordinal categories for concentration used to sort neighborhoods and used as dependent variable (range 10%). The function is used to calculate the ethnic concentration of each ethnic group and ses class

fisl <- function(y,z){
y[z >= 0.000 & z <= 0.109] <- "<10"
y[z >= 0.110 & z <= 0.209] <- "<20"
y[z >= 0.210 & z <= 0.309] <- "<30"
y[z >= 0.310 & z <= 0.409] <- "<40"
y[z >= 0.410 & z <= 0.509] <- "<50"
y[z >= 0.510 & z <= 0.609] <- "<60"
y[z >= 0.610 & z <= 0.709] <- "<70"
y[z >= 0.710 & z <= 0.809] <- "<80"
y[z >= 0.810 & z <= 0.909] <- "<90"
y[z >= 0.910 & z <= 1.000] <- "<100"
# y[z  > 1.000] <- "101"

factor(y, ordered = TRUE)
}

data$white_conc <- fisl(data$white_conc,data$frac_white)  # white concentration
data$black_conc <- fisl(data$black_conc,data$frac_black)  # black concentration
data$asian_conc <- fisl(data$asian_conc,data$frac_asian)  # asian concentration
data$diveth_class <- fisl(data$diveth_class,data$ethdiv)  # ethnic diversity according to Simpson index [0,1]
data$high_conc <- fisl(data$high_conc,data$frac_high)     # high ses concentration
data$mid_conc <- fisl(data$mid_conc,data$frac_mid)  # middle ses concentration
data$low_conc <- fisl(data$low_conc,data$frac_low)        # low ses concentration
data$divses_class <- fisl(data$divses_class,data$sesdiv)  # ses diversity according to Simpson index [0,1]





####

# selection variables to report in the dataset

data_cat <- dplyr::select(data,GEO_LABEL,frac_white,frac_black,frac_asian,frac_high,frac_mid,frac_low,white_conc, black_conc,asian_conc,diveth_class,high_conc, mid_conc,low_conc,divses_class)

# each aggregate category ethnicXses is translated into an observation row, with choice-geography repeated as many time as people live in the unit (uncount) 

wh <- data.frame(ID = paste0("wh",c(1:sum(data$w_hs))),ses = "high",ethnic = "white",uncount(data_cat,as.numeric(data$w_hs)))
 bh <- data.frame(ID = paste0("bh",c(1:sum(data$b_hs))),ses = "high",ethnic = "black",uncount(data_cat,as.numeric(data$b_hs)))
 ah <- data.frame(ID = paste0("ah",c(1:sum(data$a_hs))),ses = "high",ethnic = "asian",uncount(data_cat,as.numeric(data$a_hs)))
# 
 wm <- data.frame(ID = paste0("wm",c(1:sum(data$w_ms))),ses = "middle",ethnic = "white",uncount(data_cat,as.numeric(data$w_ms)))
 bm <- data.frame(ID = paste0("bm",c(1:sum(data$b_ms))),ses = "middle",ethnic = "black",uncount(data_cat,as.numeric(data$b_ms)))
 am <- data.frame(ID = paste0("am",c(1:sum(data$a_ms))),ses = "middle",ethnic = "asian",uncount(data_cat,as.numeric(data$a_ms)))
# 
 wl <- data.frame(ID = paste0("wl",c(1:sum(data$w_ls))),ses = "low",ethnic = "white",uncount(data_cat,as.numeric(data$w_ls)))
 bl <- data.frame(ID = paste0("bl",c(1:sum(data$b_ls))),ses = "low",ethnic = "black",uncount(data_cat,as.numeric(data$b_ls)))
 al <- data.frame(ID = paste0("al",c(1:sum(data$a_ls))),ses = "low",ethnic = "asian",uncount(data_cat,as.numeric(data$a_ls)))

 # final dataset
 
 dataset <- rbind(wh,bh,ah,wm,bm,am,wl,bl,al)
 names(dataset)[names(dataset) == 'GEO_LABEL'] <- 'choice'
 
 # to write out dataset in excel, too big
 # write.csv(dataset,file ="dataset_final")
dataset$ethnic <- as.factor(dataset$ethnic)
 dataset$ses <- as.factor(dataset$ses)

## For each observation row (ID), the ethnic or ses concentration of referred group is reported in one variable, and assigned to ordinal categories. E.g., if the ethnicity of ID is white, then the ethnic concentration is that of ethnic group white, so for each category.
 
# ethnic concentration (frac_homoe)
dataset$frac_homoe <- ifelse(dataset$ethnic == "white", dataset$frac_white,(ifelse(dataset$ethnic == "black", dataset$frac_black,dataset$frac_asian)))   
# ses concentration (frac_homos)
dataset$frac_homos <- ifelse(dataset$ses == "low", dataset$frac_low,(ifelse(dataset$ses == "middle", dataset$frac_mid,dataset$frac_high)))      

# Here the ordinary categories for ses and ethnicity are assigned
dataset$ethnic_conc <- fisl(dataset$ethnic_conc,dataset$frac_homoe)
dataset$ses_conc <- fisl(dataset$ses_conc,dataset$frac_homos)

 
 
 # objects are removed and final dataset kept
 
 keep(dataset, sure = TRUE)
 
# write.csv(dataset, file = "Brent_RP.csv", row.names = FALSE)


# hole population descriptive

dataset$ses <- factor(dataset$ses, ordered = TRUE, levels = c("low","middle","high"))

asn <- paste0("asian: ", sum(dataset$ethnic == "asian"))
bln <- paste0("black: ", sum(dataset$ethnic == "black"))
wln <- paste0("white: ", sum(dataset$ethnic == "white"))

lwn <- paste0("low: ", sum(dataset$ses == "low"))
mdn <- paste0("middle: ", sum(dataset$ses == "middle"))
hgn <- paste0("high: ", sum(dataset$ses == "high"))

ethnic_label <- c(asn,bln,wln)
names(ethnic_label) <- c("asian","black","white")

a <- ggplot(data = dataset, aes(x = ses, fill = ses)) + geom_bar(stats = 'identity',position=position_dodge()) + geom_text(aes(label = ..count..), stat = "count", vjust = 1.5, colour = "white") + facet_wrap(~ ethnic, labeller = labeller(ethnic = ethnic_label)) + scale_fill_discrete(name = "SES", labels = c(lwn,mdn,hgn)) + theme_bw()

suppressMessages(print(a))






```




```{r ordinal_logit, fig.width=10, echo=TRUE, include = TRUE}

# Ordinal logit regressions, using ethnic concentration and ses concentration as dependent variable (the ordinal category of the neighborhood people live in), and main effect of ethnicity, ses and their interaction as predictor

### Model for ethnic concentration

# to specify that the order of ethnic concentration categories is meaningful


dataset$ethnic_conc_ordered <- factor(dataset$ethnic_conc, ordered = TRUE, levels= c("<10","<20","<30","<40","<50","<60","<70","<80","<90","<100"))  

ordinal <- polr(ethnic_conc_ordered ~ ethnic*ses,data = dataset, Hess = TRUE)


# the regression model (choice based on ethnic concentration)


summary(ordinal)

# artificial dataset for estimated probability (crossing ethnicityXses for each row)
newdat <- data.frame(ethnic = rep(c("white","asian","black"),each = 3),ses =  rep(c("low","middle","high"),3))
newdat$ses <- factor(newdat$ses, levels= c("low","middle","high"))

# probability estimated (arranged for the plot on second line)
newdat <- cbind(newdat,predict(ordinal,newdat,type="probs"))
lnewdat <- melt(newdat, id.vars=c("ethnic","ses"),variable.name = "homogeneity",value.name="prob_ethnic")

# the log-odds from estimated probabilities are calculated
lnewdat<- within(lnewdat, log_odd_ethnic <- log(prob_ethnic / (1 - prob_ethnic)))

# plot of estimated probability for each category to reside in neighborhood based on ethnic concentration
e <-   ggplot(lnewdat, aes(x = homogeneity, y = prob_ethnic)) + geom_point(size = 1.5) + facet_grid(ethnic ~ ses, labeller = label_both)  + xlab("ethnic homogeneity") + ylab("probability reside") +  theme_bw() +  theme( legend.position = "bottom")
        

#### Model for ses concentration

# to specify that the order of ses concentration categories is meaningful
dataset$ses_conc_ordered <- factor(dataset$ses_conc,  ordered = TRUE, levels= c("<10","<20","<30","<40","<50","<60","<70","<80","<90","<100"))

# the regression model (choice based on ses concentration)
ordinals <- polr(ses_conc_ordered ~ ethnic*ses,data = dataset, Hess = TRUE)

summary(ordinals)

# artificial dataset for estimated probability (crossing ethnicityXses for each row)
newdats <- data.frame(ethnic = rep(c("white","asian","black"),each = 3),ses =  rep(c("low","middle","high"),3))
newdats$ses <- factor(newdats$ses, levels= c("low","middle","high"))

# probability estimated (arranged for the plot on second line)
newdats <- cbind(newdats,predict(ordinals,newdats,type="probs"))
lnewdats <- melt(newdats, id.vars=c("ethnic","ses"),variable.name = "homogeneity",value.name="prob_ses")

# the log-odds from estimated probabilities are calculated
lnewdats <- within(lnewdats, log_odd_ses <- log(prob_ses / (1 - prob_ses)))

# plot of estimated probability for each category to reside in neighborhood based on ses concentration
s <- ggplot(lnewdats, aes(x = homogeneity, y = prob_ses)) + geom_point(size = 1.5) + facet_grid(ethnic ~ ses, labeller = label_both) + xlab("ses homogeneity") + ylab("probability reside") +  theme_bw() +  theme( legend.position = "bottom")




# to print out the plots

suppressMessages(print(e))
suppressMessages(print(s))
```

```{r plot_join, fig.width=10, echo=TRUE, include = TRUE}

# dataset with probabilities and log-odds. Where log-odds is -inf, it is because probability = 0. I just added the categories no one lived in (which have probability 0) for the sake of plot. Summing probabilities for that category (ethnicityXses), the sum is 1.

lfin <- merge(lnewdat,lnewdats, by = c("ethnic","ses","homogeneity"))

# To merge the two previous plots into 1. for the plot: to stack on long format
a <- lfin %>% gather(key = subgroup, value = probab,prob_ethnic,prob_ses) %>% mutate(`type`=fct_relevel(fct_collapse(subgroup,"ethnic" = "prob_ethnic", "ses" = "prob_ses","ethnic")))

# the plot
f <- ggplot(a, aes(x = homogeneity, y = probab, color = `type`, group = `type`)) + geom_point(size = 1.5)  + geom_line() +
        facet_grid(ethnic ~ ses, labeller = label_both) + xlab("homogeneity") + ylab("probability reside") + scale_color_manual(values  = c("blue","orange"), guide = guide_legend(title="Probability to reside for type of homogeneity")) + 
        theme_bw() +  theme( legend.position = "bottom")

suppressMessages(print(f))

write.csv(lfin, file = "prob_logodds.csv", row.names = FALSE)

```
